// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6P-1xxDwxmCROWQ4ZSsWN0XenRvG1uuA',
    appId: '1:193834014425:web:908bad1503f92e0a4810c8',
    messagingSenderId: '193834014425',
    projectId: 'writer-s-assistant-5285f',
    authDomain: 'writer-s-assistant-5285f.firebaseapp.com',
    databaseURL: 'https://writer-s-assistant-5285f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'writer-s-assistant-5285f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9jvV9Y5uiPn17K7Q-l5VkdKhCx6osIDY',
    appId: '1:193834014425:android:6b000b0aef9b9ed94810c8',
    messagingSenderId: '193834014425',
    projectId: 'writer-s-assistant-5285f',
    databaseURL: 'https://writer-s-assistant-5285f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'writer-s-assistant-5285f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg_p55yUYfS5_Qd1AA-y23PqZxiHjHr5E',
    appId: '1:193834014425:ios:af5559f443194dcd4810c8',
    messagingSenderId: '193834014425',
    projectId: 'writer-s-assistant-5285f',
    databaseURL: 'https://writer-s-assistant-5285f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'writer-s-assistant-5285f.appspot.com',
    iosBundleId: 'com.example.writerAssistantFlutter',
  );
}
